async (page) => {
  const assert = (value, message) => { if (!value) throw new Error(message); };
  const reports = [];
  const route = async (path) => { await page.goto('http://glimlink.demo/#' + path); };
  const close = async () => { await page.getByRole('button', { name: 'Fermer la fenêtre' }).click(); };
  const layout = async (name) => {
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Débordement page : ' + name);
    const dialog = page.getByRole('dialog');
    if (await dialog.count()) assert(await dialog.evaluate((el) => el.scrollWidth <= el.clientWidth), 'Débordement modal : ' + name);
  };
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    await page.evaluate(() => localStorage.clear()); await page.reload();
    await route('/company/new-need?need=need-admin');
    await page.locator('[name="missions"]').fill('Suivre les commandes corrigées');
    await page.getByRole('group', { name: 'Compétences proposées à confirmer' }).locator('.choice-options > summary').click();
    await page.getByRole('group', { name: 'Compétences proposées à confirmer' }).getByLabel('Relation client', { exact: true }).check();
    await page.getByRole('group', { name: 'Domaines envisagés' }).locator('.choice-options > summary').click();
    await page.getByRole('group', { name: 'Domaines envisagés' }).getByLabel('Commerce', { exact: true }).check();
    await page.locator('[name="mobility"]').selectOption('Déplacements locaux');
    await page.locator('[name="wishes"]').fill('Une expérience en boutique souhaitable');
    await page.locator('#confirm-brief').check();
    await page.getByRole('button', { name: 'C’est exactement ça' }).click();
    await route('/adviser/needs');
    const brief = page.locator('.adviser-need').filter({ hasText: 'Accueil & gestion administrative' });
    assert((await brief.innerText()).includes('Suivre les commandes corrigées'), 'Missions corrigées absentes du brief conseiller');
    assert((await brief.innerText()).includes('Relation client'), 'Compétences absentes du brief conseiller');
    assert((await brief.innerText()).includes('boutique souhaitable'), 'Souhaitables absents du brief conseiller');
    await layout('Brief partagé');
    await route('/adviser/students');
    await page.locator('.student-row').filter({ hasText: 'Sophie' }).getByRole('button', { name: 'Ouvrir la fiche' }).click();
    await page.locator('[name="mobility"]').selectOption('Jusqu’à 30 km du domicile');
    await page.getByRole('button', { name: 'Enregistrer le brouillon' }).click(); await close();
    assert((await page.locator('.student-row').filter({ hasText: 'Sophie' }).innerText()).includes('Corrections à valider'), 'Correction publiée non repérée');
    await route('/adviser/home');
    await page.locator('.metrics button').filter({ hasText: 'à vérifier' }).click();
    assert(await page.locator('select[name="status"]').inputValue() === 'pending', 'Compteur non filtré');
    assert((await page.locator('.student-list').innerText()).includes('Sophie'), 'Profil corrigé absent du filtre');
    await page.locator('.student-row').filter({ hasText: 'Sophie' }).getByRole('button', { name: 'Ouvrir la fiche' }).click();
    assert((await page.locator('.pending-comparison').innerText()).includes('Jusqu’à 30 km du domicile'), 'Comparaison des corrections absente');
    await page.locator('#student-confirmation').check();
    await page.getByRole('button', { name: 'Valider et publier' }).click();
    await route('/company/discover?need=need-admin');
    await page.locator('.talent-card').filter({ hasText: 'Sophie' }).getByRole('button', { name: 'Voir le profil' }).click();
    assert((await page.getByRole('dialog').innerText()).includes('Jusqu’à 30 km du domicile'), 'Mobilité publiée absente');
    assert(!(await page.getByRole('dialog').innerText()).includes('Mobilité locale'), 'Mobilité inventée');
    assert((await page.getByRole('dialog').innerText()).includes('Mathilde JEANNE'), 'Validateur absent');
    await page.getByRole('button', { name: 'Année', exact: true }).click();
    assert(await page.locator('.year-month').count() === 12, 'Vue annuelle entreprise absente');
    await layout('Calendrier entreprise'); await close();
    await route('/company/selections');
    await page.getByRole('button', { name: 'Demander une mise en relation' }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Demander une mise en relation' }).click();
    await page.evaluate(() => {
      const key = 'glimlink-prototype-v1'; const store = JSON.parse(localStorage.getItem(key));
      const selected = store.students.find((s) => s.id === store.requests[0].studentIds[0]);
      selected.published.availableFrom = '2027-03-01';
      store.calendars.find((c) => c.id === selected.published.trainingId).exceptions = [{ id: 'test-exception', start: '2026-11-06', end: '2026-11-06', kind: 'course', label: 'Cours exceptionnel' }];
      store.needs[0].missions = ['Mission modifiée après demande'];
      store.needs.push({ ...store.needs[0], id: 'foreign-need', title: 'BESOIN HORS PERIMETRE', schools: ['campus-b'] });
      store.requests.push({ id: 'foreign-request', needId: 'foreign-need', studentIds: [store.students.find((s) => s.school === 'campus-b').id], message: 'DEMANDE HORS PERIMETRE', date: '', status: 'received' });
      localStorage.setItem(key, JSON.stringify(store));
    }); await page.reload();
    await route('/adviser/home');
    assert(!(await page.locator('main').innerText()).includes('HORS PERIMETRE'), 'Besoin étranger dans le dashboard');
    await route('/adviser/requests');
    const request = page.locator('.request-card').first();
    assert((await request.innerText()).includes('calendrier modifié'), 'Changement de calendrier absent');
    assert((await request.innerText()).includes('brief a été modifié'), 'Changement de brief absent');
    assert(!(await page.locator('main').innerText()).includes('HORS PERIMETRE'), 'Demande étrangère exposée');
    await page.locator('[name="followUp"]').fill('NOTE CONSEILLER CONFIDENTIELLE');
    await page.locator('[name="meetingDate"]').fill('2026-11-10T14:00');
    await layout('Demande conseiller');
    await route('/company/requests');
    assert(!(await page.locator('main').innerText()).includes('NOTE CONSEILLER CONFIDENTIELLE'), 'Note conseiller affichée à l’entreprise');
    await page.getByLabel('Entreprise de démonstration').selectOption('bloom-studio');
    assert((await page.locator('h1').innerText()).includes('Thomas'), 'Compte entreprise fixe');
    await route('/company/needs');
    assert(!(await page.locator('main').innerText()).includes('Accueil & gestion administrative'), 'Besoin d’une autre entreprise exposé');
    await layout('Second partenaire');
    await page.getByLabel('Entreprise de démonstration').selectOption('maison-alba');
    await page.evaluate(() => {
      const key = 'glimlink-prototype-v1'; const store = JSON.parse(localStorage.getItem(key));
      store.needs[0].requiredDays = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi']; store.needs[0].passed = [];
      localStorage.setItem(key, JSON.stringify(store));
    }); await page.reload(); await route('/company/discover?need=need-admin');
    assert(await page.locator('.relaxation-option').count() > 0, 'Absence de propositions chiffrées');
    await layout('Aucun résultat');
    await page.getByRole('button', { name: 'Revoir cette proposition et confirmer' }).first().click();
    assert(await page.locator('#confirm-brief').isChecked() === false, 'Assouplissement validé automatiquement');
    await route('/adviser/companies');
    await page.getByRole('button', { name: 'Inviter une entreprise' }).click();
    await page.locator('[name="companyName"]').fill('Partenaire audit');
    await page.locator('[name="email"]').fill('audit@example.com');
    await page.getByRole('button', { name: 'Préparer l’invitation' }).click();
    await page.getByRole('button', { name: 'Explorer l’activation du compte' }).click();
    for (const [name, value] of Object.entries({ siret: '12345678901234', address: 'Adresse fictive', contact: 'Alex Exemple', phone: '0000000000', email: 'audit@example.com' })) await page.locator(`[name="${name}"]`).fill(value);
    await page.locator('[name="sector"]').selectOption('Services aux entreprises');
    await page.locator('[name="position"]').selectOption('Direction');
    await page.getByRole('button', { name: 'Vérifier mon e-mail' }).click();
    await page.getByRole('button', { name: 'Simuler la vérification de l’e-mail' }).click();
    await page.getByRole('button', { name: 'Fermer l’aperçu' }).click();
    assert((await page.locator('.company-card').filter({ hasText: 'Partenaire audit' }).innerText()).includes('Compte activé'), 'Partenaire non activé');
    await page.reload();
    assert(await page.locator('.company-card').filter({ hasText: 'Partenaire audit' }).count() === 1, 'Invitation non persistante');
    await layout('Invitation persistante');
    if (width < 768) {
      await route('/adviser/home');
      await page.getByRole('button', { name: /Plus.*Demandes et entreprises/ }).click();
      await page.getByRole('link', { name: 'Entreprises partenaires', exact: true }).click();
      await page.getByRole('heading', { name: 'Des partenaires, des opportunités.' }).waitFor();
      assert(await page.locator('#mobile-more-links').count() === 0, 'Menu mobile non refermé');
      await page.getByRole('button', { name: /Plus.*Demandes et entreprises/ }).click();
      await page.getByRole('link', { name: /Demandes à traiter/ }).click();
      await page.getByRole('heading', { name: 'Vous faites la rencontre.' }).waitFor();
    }
    reports.push({ width, status: 'pass', scenarios: ['brief corrigé', 'corrections en attente', 'mobilité et validateur', 'calendrier annuel entreprise', 'changements après demande', 'périmètre conseiller', 'notes privées', 'entreprises séparées', 'aide sans résultat', 'invitation persistante'] });
  }
  await page.evaluate(() => localStorage.clear()); await page.reload();
  return reports;
}
